[Comgr][hotswap] Fix undefined reference to llvm::Triple(std::string...)
Add missing library: TargetParser

```
/usr/bin/ld:
tools/comgr/src/hotswap/CMakeFiles/hotswap-transpiler.dir/raiser.cpp.o:
undefined reference to symbol
'_ZN4llvm6TripleC1EONSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'
```